kind: Deployment
apiVersion: apps/v1
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftWebConsole
  name: onderhoud

  namespace: hetarchief
  labels:
    app.openshift.io/runtime-namespace: hetarchief
    app: client
    app.kubernetes.io/part-of: hetarchief-prd
    app.kubernetes.io/instance: onderhoud
    app.kubernetes.io/component: onderhoud
    app.openshift.io/runtime: onderhoud
    app.kubernetes.io/name: onderhoud
    component: frontent
    app.openshift.io/runtime-version: prd
spec:
  replicas: 0
  selector:
    matchLabels:
      app: onderhoud
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: onderhoud
        component: frontent
        deploymentconfig: onderhoud
      annotations:
        openshift.io/generated-by: OpenShiftWebConsole
    spec:
      containers:
        - resources:
            limits:
              cpu: 200m
              memory: 128Mi
            requests:
              cpu: 50m
              memory: 64Mi
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 11
            timeoutSeconds: 4
            periodSeconds: 55
            successThreshold: 1
            failureThreshold: 6
          terminationMessagePath: /dev/termination-log
          name: onderhoud
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
              scheme: HTTP
            timeoutSeconds: 1
            periodSeconds: 70
            successThreshold: 1
            failureThreshold: 3
          env:
            - name: MAINTENANCE
              value: 'true'
          ports:
            - containerPort: 8080
              protocol: TCP
          imagePullPolicy: IfNotPresent
          terminationMessagePolicy: File
          image: >-
            image-registry.openshift-image-registry.svc:5000/hetarchief/onderhoud:prd
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
